# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ElementObject": "00_core.ipynb",
         "Flux": "01_physics.ipynb"}

modules = ["core.py",
           "physics.py"]

doc_url = "https://cfgarciar.github.io/"

git_url = "https://github.com/cfgarciar/geomechy/tree/master/"

def custom_doc_links(name): return None
