# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['MaterialManager', 'NodeSet']

# Cell
from .base import ItemDict

# Cell
class MaterialManager(list):

    def __init__(self, matProps):
        matType = matProps.type
        exec(f'from geomechy.materials import {matType} as material', globals())
        self.mat = material(matProps)
        self.iIter = -1

    def reset(self):
        self.iIter = -1

    def getStress(self, kinematic, iSam=-1):

        if iSam == -1:
            self.iIter += 1
            iSam = self.iIter

        self.mat.setIter(iSam)
        return self.mat.getStress(kinematic)

    def commitHistory(self):
        self.mat.commitHistory()

# Cell
class NodeSet(ItemDict):

    def getNodeCoords(self, nodeIds):
        return np.array(self.get(nodeIds))

    def readFromAbaqus(self, fileName):
        fin = open( fileName )

    def readFromJson(self, fileName):
        fin = open( fileName )