# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['ElementObject', 'ElementObject']

# Cell
class ElementObject:
    "Save important information of each element in the mesh"

    def __init__(self, elemId, elemType='default', reduced=True, physic='default'):
        self.elemId = elemId
        self.elemtype = elemType
        self.reduced = reduced
        self.physic = physic

    def __str__(self):
        return f"Element id: {self.elemID}\n Element Type: {self.elemType}\n"

# Cell
class ElementObject:
    "Save important information of each element in the mesh"

    def __init__(self, elemId, elemType='default', reduced=True, physic='default'):
        self.elemId = elemId
        self.elemtype = elemType
        self.reduced = reduced
        self.physic = physic

    def __str__(self):
        return f"Element id: {self.elemID}\n Element Type: {self.elemType}\n"