# AUTOGENERATED! DO NOT EDIT! File to edit: 06_materials.ipynb (unless otherwise specified).

__all__ = ['Soil', 'Rock', 'Water', 'Oil', 'Air', 'Gas', 'Soil']

# Cell
from .base import Properties
from .utils import *
from .io import jsonReader

# Cell
class Soil(Properties):
    def __init__ (self, props={}):

        for key in props.keys():
            setattr(self, key, props[key])

        for att in dir(self):
            if att.startswith('__') or att.startswith('store') or att.startswith('Type') or att.startswith('name'):
                continue

            dim = eval(getattr(self,att)["dim"])
            value = getattr(self,att)["value"]
            setattr(self, att, value*dim)


# Cell
class Rock(Properties):
    def __init__ (self, props={}):

        for key in props.keys():
            setattr(self, key, props[key])

        for att in dir(self):
            if att.startswith('__') or att.startswith('store') or att.startswith('Type') or att.startswith('name'):
                continue

            dim = eval(getattr(self,att)["dim"])
            value = getattr(self,att)["value"]
            setattr(self, att, value*dim)

# Cell
class Water(Properties):
    def __init__ (self, props={}):

        for key in props.keys():
            setattr(self, key, props[key])

        for att in dir(self):
            if att.startswith('__') or att.startswith('store') or att.startswith('Type') or att.startswith('name'):
                continue

            dim = eval(getattr(self,att)["dim"])
            value = getattr(self,att)["value"]
            setattr(self, att, value*dim)

# Cell
class Oil(Properties):
    def __init__ (self, props={}):

        for key in props.keys():
            setattr(self, key, props[key])

        for att in dir(self):
            if att.startswith('__') or att.startswith('store') or att.startswith('Type') or att.startswith('name'):
                continue

            dim = eval(getattr(self,att)["dim"])
            value = getattr(self,att)["value"]
            setattr(self, att, value*dim)

# Cell
class Air(Properties):
    def __init__ (self, props={}):

        for key in props.keys():
            setattr(self, key, props[key])

        for att in dir(self):
            if att.startswith('__') or att.startswith('store') or att.startswith('Type') or att.startswith('name'):
                continue

            dim = eval(getattr(self,att)["dim"])
            value = getattr(self,att)["value"]
            setattr(self, att, value*dim)

# Cell
class Gas(Properties):
    def __init__ (self, props={}):

        for key in props.keys():
            setattr(self, key, props[key])

        for att in dir(self):
            if att.startswith('__') or att.startswith('store') or att.startswith('Type') or att.startswith('name'):
                continue

            dim = eval(getattr(self,att)["dim"])
            vvalue = getattr(self,att)["value"]
            setattr(self, att, value*dim)

# Cell
class Soil(Properties):
    def __init__ (self, props={}):

        for key in props.keys():
            setattr(self, key, props[key])

        for att in dir(self):
            if att.startswith('__') or att.startswith('store') or att.startswith('Type') or att.startswith('name'):
                continue

            dim = eval(getattr(self,att)["dim"])
            value = getattr(self,att)["value"]
            setattr(self, att, value*dim)