# AUTOGENERATED! DO NOT EDIT! File to edit: 01_physics.ipynb (unless otherwise specified).

__all__ = ['SmallStrainContinuum']

# Cell
from .base import BaseElement
from .core import NodeSet

# Cell
class SmallStrainContinuum(BaseElement):

    dofTypes = ['u', 'v']

    def __init__(self, nodes, props):
        BaseElement.__init__(self, nodes, props)

    def __type__(self):
        return name