# AUTOGENERATED! DO NOT EDIT! File to edit: 10_utils.ipynb (unless otherwise specified).

__all__ = ['pico', 'nano', 'micro', 'milli', 'centi', 'deci', 'kilo', 'mega', 'giga', 'tera', 'meter', 'ft', 'inch',
           'kg', 'gram', 'pound', 'Ton', 'second', 'minute', 'hour', 'day', 'year', 'Kelvin', 'Rankine', 'Celsius',
           'Fahrenheit', 'litre', 'gallon', 'stb', 'Joules', 'btu', 'Cal', 'centiPoise', 'Poise', 'centiStokes',
           'Stokes', 'milliDarcy', 'Darcy', 'inch_second', 'mm_second']

# Cell
pico  = 1.e-12
nano  = 1.e-9
micro = 1.e-6
milli = 1.e-3
centi = 1.e-2
deci  = 1.e-1
kilo  = 1.e+3
mega  = 1.e+6
giga  = 1.e+9
tera  = 1.e+12

# Cell
meter = 1.                #meters -> meters
ft    = 0.3048*meter      #foots  -> meters
inch  = 2.54*centi*meter  #inches -> meters

# Cell
kg     = 1.              #kilograms  -> kilograms
gram   = 1.*kg           #grams      -> kilograms
pound  = 0.45359237*kg   #pounds     -> kilograms
Ton    = 1000.*kg        #Tons       -> kilograms

# Cell
second  = 1.           #seconds -> seconds
minute  = 60.*second   #minutes -> seconds
hour    = 60.*minute   #hours   -> seconds
day     = 24.*hour     #days    -> seconds
year    = 365.25*day   #years   -> seconds

# Cell
Kelvin     = 1                             #kelvin     -> kelvin
Rankine    = 5./9.                         #rankine    -> kelvin
Celsius    = lambda C: C+273.15            #celsius    -> kelvin
Fahrenheit = lambda F: (F+459.67)*Rankine  #fahrenheit -> kelvin

# Cell
litre  = (deci*meter)**3  #litre            -> cubic meter
gallon = 231*inch**3      #US gallons       -> cubic meter
stb    = 42*gallon        #standard barrels -> cubic meter

# Cell
Joules   = 1.             #Joules -> Joules
btu     = 1054.06*Joules  #British thermal unit -> Joules
Cal     = 4184.*Joules    #Calories -> Joules

# Cell
centiPoise = milli*Pascal*second  #centiPoise -> Pascal*second
Poise      = 100*centiPoise       #Poise      -> Pascal*second

# Cell
centiStokes = 1.E-6*(meter**2)/second  #centiStokes -> square-meter per second
Stokes      = 1.E-4*(meter**2)/second  #centipoise  -> square-meter per second

# Cell
milliDarcy = 9.869233e-16*(meter**2)  #milliDarcy -> square-meter
Darcy      = 9.869233e-13*(meter**2)  #Darcy      -> square-meter

# Cell
inch_second = inch*second         #inches per second      -> meter per second
mm_second   = milli*meter*second  #millimeters per second -> meter per second